### PR TITLE
Feature add ssl

### LINKED ISSUE #15: Add SSL/TLS support
Add SSL/TLS support to syslog output plugin.

This was originally requested in https://logstash.jira.com/browse/LOGSTASH-618

### PR DESCRIPTION
**Pull request by breml**
Ported SSL implementation from https://github.com/logstash-plugins/logstash-output-tcp/pull/3
with inspiration from https://github.com/aaw/logstash-output-syslog/commit/ae091c0b0b7dc75b27b7e336e87f24e11ba99360

Fixes #15

### CODE REVIEW

**Comment by breml** [comment]
Could please someone give me some feedback?

**Comment by breml** [comment]
@jsvd Would you mind to have a look at this one as well (or may be #6)?

**Comment by suyograo** [comment]
LGTM

**Comment by suyograo** [comment]
@breml can you rebase from master? I am geting conflicts

**Comment by breml** [comment]
@suyograo I just rebased this one. I will wait with the rebase of #17 until this one is merged. (Over the last two months I resolved the same merge conflicts over and over again to keep my own branch in sync with master on one side and to get my pull requests merged on the other.)

**Pull request closed without merging**
