### PR TITLE
Add relay mode

### PR DESCRIPTION
**Pull request by zacblazic**
Allows messages to be passed through as-is, without tainting them with extra fields such as priority, timestamp, source host etc.

This is useful for shipping pristine logs to services which need to parse them as if they were sent directly from their source.

### CODE REVIEW

**Comment by zacblazic** [comment]
I've signed the CLA, unsure why the check has failed.

**Comment by breml** [comment]
@zacblazic I just wondering, if in this case the logstash-output-tcp would work?

**Comment by jordansissel** [comment]
+1 on using the tcp output for this.

In the syslog space, the term `relay` refers to a specific role that has certain behaviors that are more complex than the behavior implemented in this patch.

**Comment by zacblazic** [comment]
> @zacblazic I just wondering, if in this case the logstash-output-tcp would work?

Man, now I just feel stupid.

This works perfectly for my use case:
```
tcp {
  host => ["${SYSLOG_HOST}"]
  port => "${SYSLOG_PORT:514}"
  codec => "line"
}
```

> In the syslog space, the term relay refers to a specific role that has certain behaviors that are more complex than the behavior implemented in this patch.

Agreed.

**Comment by zacblazic** [comment]
Closing as this can be achieved by using the `logstash-output-tcp` plugin instead.

**Pull request closed without merging**
